### ISSUE TITLE
CreateAliasForType does not account for SQL keywords

### ISSUE THREAD

**Issue by jaalu** [DIPSAS/FluentDbTools#15]
Attempting to construct a query for all fields of an object `AggressiveStork`

```
var sql = SqlBuilder
                .Select()
                .Fields<AggressiveStork>(x => x.All())
                .OnSchema(DbConfig.Schema)
                .Build();
```
leads to SqlBuilder constructing the query
```
SELECT as.* FROM AggressiveStork as
```
In Postgres, the final `as` is interpreted as the SQL keyword `AS`, causing a syntax error.

**Comment by aho-dips** [comment]
This should be fixed
